apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: reforma
  name: reforma-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reforma-manager-role
subjects:
- kind: ServiceAccount
  name: reforma-controller-manager
  namespace: reforma-system

