# permissions for end users to edit patches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-editor-role
rules:
- apiGroups:
  - reforma.prosimcorp.com
  resources:
  - patches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reforma.prosimcorp.com
  resources:
  - patches/status
  verbs:
  - get
