# permissions for end users to view patches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-viewer-role
rules:
- apiGroups:
  - reforma.prosimcorp.com
  resources:
  - patches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - reforma.prosimcorp.com
  resources:
  - patches/status
  verbs:
  - get
