apiVersion: reforma.prosimcorp.com/v1alpha1
kind: Patch
metadata:
  name: patch-sample
spec:
  #periodical: true
  #synchronizationTime: 10s

  sources:
    - apiVersion: v1
      kind: ConfigMap
      name: cluster-info-dos
      namespace: default
    - apiVersion: v1
      kind: ConfigMap
      name: cluster-info-tres
      namespace: default

  target:
    apiVersion: v1
    kind: ConfigMap
    name: cluster-info
    namespace: default

  patchType: application/json-patch+json

  template: |
    {{- $target := (index . 0) -}}
    {{- $source := (index . 1) -}}

    {{/* Get the original flags of the target */}}
    {{/* - $target_args := (index $target.spec.template.spec.containers 0).args - */}}

    {{/* Flags for all the cloud providers */}}
    {{/* - $target_args = append $target_args "--tcp-services-configmap=gitlab/ingress-nginx-tcp-services" - */}}

    - op: replace
      path: /spec/template/spec/containers/0/args
      value:
        {{- $source.metadata.name -}}
        {{/* - $target_args | uniq | toYaml | nindent 4 - */}}

