apiVersion: reforma.prosimcorp.com/v1alpha1
kind: Patch
metadata:
  name: patch-sample
spec:
  #periodical: true
  #synchronizationTime: 10s

  sources:
    - apiVersion: v1
      kind: ConfigMap
      name: cluster-info-dos
      namespace: default
    - apiVersion: v1
      kind: ConfigMap
      name: cluster-info-tres
      namespace: default

  target:
    apiVersion: v1
    kind: ConfigMap
    name: cluster-info
    namespace: default

  patchType: application/json-patch+json

  template: |
    {{- $target := (index . 0) -}}

    {{- $source := (index . 1) -}}


    - op: add
      path: /metadata/annotations/testiando
      value: "{{- $source.data.primero -}}"
