apiVersion: reforma.prosimcorp.com/v1alpha1
kind: Patch
metadata:
  name: patch-sample
spec:
  # Synchronization parameters
  synchronization:
    time: "5s"

  # Sources to look for the data to make wonderful patches
  sources:
    - apiVersion: v1
      kind: ConfigMap
      name: cluster-info-dos
      namespace: default
    - apiVersion: v1
      kind: ConfigMap
      name: cluster-info-tres
      namespace: default

  # Target to apply patches to
  target:
    apiVersion: v1
    kind: ConfigMap
    name: cluster-info
    namespace: default

  # You know, the patch type
  patchType: application/json-patch+json

  # Template to craft the patch. TODO
  template: |
    {{- $target := (index . 0) -}}
    {{- $source := (index . 1) -}}

    - op: add
      path: /metadata/annotations/testiando
      value: "{{- $source.metadata.name -}}"
